CREATE TABLE public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  s3_path TEXT NULL,
  readable_filename TEXT NULL,
  course_name TEXT NULL,
  url TEXT NULL,
  contexts JSONB NULL,
  base_url TEXT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS documents_course_name_idx ON public.documents USING hash (course_name) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS documents_created_at_idx ON public.documents USING btree (created_at) TABLESPACE pg_default;
